/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Assert;
import org.junit.Test;

import java.io.IOException;
import java.net.URISyntaxException;
import java.util.Optional;

import static org.junit.Assert.*;

public class PokeProcessorTests {
    @Test
    public void allPokemonShouldBeLoadedIntoMemory() throws IOException, URISyntaxException {
        //Setup
        Integer expected = 245;
        PokeProcessor classUnderTest = new PokeProcessor();
        
        //Execute
        classUnderTest.loadPokemons(Optional.empty());
        Integer actual = classUnderTest.getPokemonCount();

        //Assert
        Assert.assertEquals("should be 251 pokemon",expected,actual);
        //Teardown
    }

}
